### ISSUE TITLE
Bug in int wmain()

### ISSUE THREAD

**Issue by DavidPetr** [amirkhaniansev/os-experiments#2]
Instead of WaitForMultipleObjects(2, producers, TRUE, INFINITE); must be WaitForMultipleObjects(PRODUCERS_COUNT, producers, TRUE, INFINITE);
and accordingly there must be WaitForMultipleObjects(CONSUMER_COUNT, consumers, TRUE, INFINITE);

**Comment by amirkhaniansev** [comment]
Ok, thanks, I'll fix it now.
